USE [PROJECT]
GO

/****** Object:  Table [dbo].[BOOKING]    Script Date: 28-11-2018 02:20:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BOOKING](
	[BOOKING_NO] [bigint] IDENTITY(1,1) NOT NULL,
	[CID] [bigint] NOT NULL,
	[ROOM_NO] [int] NOT NULL,
	[QUANTITY] [int] NOT NULL,
	[FROM_DATE] [date] NOT NULL,
	[TO_DATE] [date] NOT NULL,
	[BOOKED_DATE] [date] NOT NULL,
 CONSTRAINT [PK_BOOKING] PRIMARY KEY CLUSTERED 
(
	[BOOKING_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BOOKING]  WITH CHECK ADD  CONSTRAINT [FK_ROOMNO_BOOKING_ROOMS] FOREIGN KEY([ROOM_NO])
REFERENCES [dbo].[ROOMS] ([ROOM_NO])
GO

ALTER TABLE [dbo].[BOOKING] CHECK CONSTRAINT [FK_ROOMNO_BOOKING_ROOMS]
GO

