USE [PROJECT]
GO

/****** Object:  Table [dbo].[ROOMS]    Script Date: 28-11-2018 02:21:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ROOMS](
	[ROOM_NO] [int] IDENTITY(1,1) NOT NULL,
	[ROOM_TYPE] [nvarchar](50) NOT NULL,
	[PRICE] [float] NOT NULL,
	[ROOM_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ROOMS] PRIMARY KEY CLUSTERED 
(
	[ROOM_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ROOMS]  WITH CHECK ADD  CONSTRAINT [FK_ROOMS_ROOMS] FOREIGN KEY([ROOM_NO])
REFERENCES [dbo].[ROOMS] ([ROOM_NO])
GO

ALTER TABLE [dbo].[ROOMS] CHECK CONSTRAINT [FK_ROOMS_ROOMS]
GO

