//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiltonHotel.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.web.com.assignment3", ConfigurationName="ServiceReference1.Assignment3")]
    public interface Assignment3 {
        
        // CODEGEN: Generating message contract since element name id from namespace http://service.web.com.assignment3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MiltonHotel.ServiceReference1.removeResponse remove(MiltonHotel.ServiceReference1.removeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.removeResponse> removeAsync(MiltonHotel.ServiceReference1.removeRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://service.web.com.assignment3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MiltonHotel.ServiceReference1.getResponse get(MiltonHotel.ServiceReference1.getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getResponse> getAsync(MiltonHotel.ServiceReference1.getRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://service.web.com.assignment3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MiltonHotel.ServiceReference1.updateResponse update(MiltonHotel.ServiceReference1.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.updateResponse> updateAsync(MiltonHotel.ServiceReference1.updateRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://service.web.com.assignment3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MiltonHotel.ServiceReference1.createResponse create(MiltonHotel.ServiceReference1.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.createResponse> createAsync(MiltonHotel.ServiceReference1.createRequest request);
        
        // CODEGEN: Generating message contract since element name getAllReturn from namespace http://service.web.com.assignment3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MiltonHotel.ServiceReference1.getAllResponse getAll(MiltonHotel.ServiceReference1.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getAllResponse> getAllAsync(MiltonHotel.ServiceReference1.getAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="remove", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.removeRequestBody Body;
        
        public removeRequest() {
        }
        
        public removeRequest(MiltonHotel.ServiceReference1.removeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class removeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public removeRequestBody() {
        }
        
        public removeRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeResponse", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.removeResponseBody Body;
        
        public removeResponse() {
        }
        
        public removeResponse(MiltonHotel.ServiceReference1.removeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class removeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string removeReturn;
        
        public removeResponseBody() {
        }
        
        public removeResponseBody(string removeReturn) {
            this.removeReturn = removeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.getRequestBody Body;
        
        public getRequest() {
        }
        
        public getRequest(MiltonHotel.ServiceReference1.getRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class getRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public getRequestBody() {
        }
        
        public getRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResponse", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.getResponseBody Body;
        
        public getResponse() {
        }
        
        public getResponse(MiltonHotel.ServiceReference1.getResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class getResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getReturn;
        
        public getResponseBody() {
        }
        
        public getResponseBody(string getReturn) {
            this.getReturn = getReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(MiltonHotel.ServiceReference1.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string choice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string value;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(string id, string choice, string value) {
            this.id = id;
            this.choice = choice;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(MiltonHotel.ServiceReference1.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class updateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateReturn;
        
        public updateResponseBody() {
        }
        
        public updateResponseBody(string updateReturn) {
            this.updateReturn = updateReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="create", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.createRequestBody Body;
        
        public createRequest() {
        }
        
        public createRequest(MiltonHotel.ServiceReference1.createRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class createRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nameOnCard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string unitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string quantity;
        
        public createRequestBody() {
        }
        
        public createRequestBody(string id, string cardNumber, string expDate, string nameOnCard, string unitPrice, string quantity) {
            this.id = id;
            this.cardNumber = cardNumber;
            this.expDate = expDate;
            this.nameOnCard = nameOnCard;
            this.unitPrice = unitPrice;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createResponse", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.createResponseBody Body;
        
        public createResponse() {
        }
        
        public createResponse(MiltonHotel.ServiceReference1.createResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class createResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createReturn;
        
        public createResponseBody() {
        }
        
        public createResponseBody(string createReturn) {
            this.createReturn = createReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(MiltonHotel.ServiceReference1.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://service.web.com.assignment3", Order=0)]
        public MiltonHotel.ServiceReference1.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(MiltonHotel.ServiceReference1.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.web.com.assignment3")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllReturn;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(string getAllReturn) {
            this.getAllReturn = getAllReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Assignment3Channel : MiltonHotel.ServiceReference1.Assignment3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment3Client : System.ServiceModel.ClientBase<MiltonHotel.ServiceReference1.Assignment3>, MiltonHotel.ServiceReference1.Assignment3 {
        
        public Assignment3Client() {
        }
        
        public Assignment3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiltonHotel.ServiceReference1.removeResponse MiltonHotel.ServiceReference1.Assignment3.remove(MiltonHotel.ServiceReference1.removeRequest request) {
            return base.Channel.remove(request);
        }
        
        public string remove(string id) {
            MiltonHotel.ServiceReference1.removeRequest inValue = new MiltonHotel.ServiceReference1.removeRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.removeRequestBody();
            inValue.Body.id = id;
            MiltonHotel.ServiceReference1.removeResponse retVal = ((MiltonHotel.ServiceReference1.Assignment3)(this)).remove(inValue);
            return retVal.Body.removeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.removeResponse> MiltonHotel.ServiceReference1.Assignment3.removeAsync(MiltonHotel.ServiceReference1.removeRequest request) {
            return base.Channel.removeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.removeResponse> removeAsync(string id) {
            MiltonHotel.ServiceReference1.removeRequest inValue = new MiltonHotel.ServiceReference1.removeRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.removeRequestBody();
            inValue.Body.id = id;
            return ((MiltonHotel.ServiceReference1.Assignment3)(this)).removeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiltonHotel.ServiceReference1.getResponse MiltonHotel.ServiceReference1.Assignment3.get(MiltonHotel.ServiceReference1.getRequest request) {
            return base.Channel.get(request);
        }
        
        public string get(string id) {
            MiltonHotel.ServiceReference1.getRequest inValue = new MiltonHotel.ServiceReference1.getRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.getRequestBody();
            inValue.Body.id = id;
            MiltonHotel.ServiceReference1.getResponse retVal = ((MiltonHotel.ServiceReference1.Assignment3)(this)).get(inValue);
            return retVal.Body.getReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getResponse> MiltonHotel.ServiceReference1.Assignment3.getAsync(MiltonHotel.ServiceReference1.getRequest request) {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getResponse> getAsync(string id) {
            MiltonHotel.ServiceReference1.getRequest inValue = new MiltonHotel.ServiceReference1.getRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.getRequestBody();
            inValue.Body.id = id;
            return ((MiltonHotel.ServiceReference1.Assignment3)(this)).getAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiltonHotel.ServiceReference1.updateResponse MiltonHotel.ServiceReference1.Assignment3.update(MiltonHotel.ServiceReference1.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public string update(string id, string choice, string value) {
            MiltonHotel.ServiceReference1.updateRequest inValue = new MiltonHotel.ServiceReference1.updateRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.updateRequestBody();
            inValue.Body.id = id;
            inValue.Body.choice = choice;
            inValue.Body.value = value;
            MiltonHotel.ServiceReference1.updateResponse retVal = ((MiltonHotel.ServiceReference1.Assignment3)(this)).update(inValue);
            return retVal.Body.updateReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.updateResponse> MiltonHotel.ServiceReference1.Assignment3.updateAsync(MiltonHotel.ServiceReference1.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.updateResponse> updateAsync(string id, string choice, string value) {
            MiltonHotel.ServiceReference1.updateRequest inValue = new MiltonHotel.ServiceReference1.updateRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.updateRequestBody();
            inValue.Body.id = id;
            inValue.Body.choice = choice;
            inValue.Body.value = value;
            return ((MiltonHotel.ServiceReference1.Assignment3)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiltonHotel.ServiceReference1.createResponse MiltonHotel.ServiceReference1.Assignment3.create(MiltonHotel.ServiceReference1.createRequest request) {
            return base.Channel.create(request);
        }
        
        public string create(string id, string cardNumber, string expDate, string nameOnCard, string unitPrice, string quantity) {
            MiltonHotel.ServiceReference1.createRequest inValue = new MiltonHotel.ServiceReference1.createRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.createRequestBody();
            inValue.Body.id = id;
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.expDate = expDate;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.quantity = quantity;
            MiltonHotel.ServiceReference1.createResponse retVal = ((MiltonHotel.ServiceReference1.Assignment3)(this)).create(inValue);
            return retVal.Body.createReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.createResponse> MiltonHotel.ServiceReference1.Assignment3.createAsync(MiltonHotel.ServiceReference1.createRequest request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.createResponse> createAsync(string id, string cardNumber, string expDate, string nameOnCard, string unitPrice, string quantity) {
            MiltonHotel.ServiceReference1.createRequest inValue = new MiltonHotel.ServiceReference1.createRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.createRequestBody();
            inValue.Body.id = id;
            inValue.Body.cardNumber = cardNumber;
            inValue.Body.expDate = expDate;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.quantity = quantity;
            return ((MiltonHotel.ServiceReference1.Assignment3)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MiltonHotel.ServiceReference1.getAllResponse MiltonHotel.ServiceReference1.Assignment3.getAll(MiltonHotel.ServiceReference1.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public string getAll() {
            MiltonHotel.ServiceReference1.getAllRequest inValue = new MiltonHotel.ServiceReference1.getAllRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.getAllRequestBody();
            MiltonHotel.ServiceReference1.getAllResponse retVal = ((MiltonHotel.ServiceReference1.Assignment3)(this)).getAll(inValue);
            return retVal.Body.getAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getAllResponse> MiltonHotel.ServiceReference1.Assignment3.getAllAsync(MiltonHotel.ServiceReference1.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<MiltonHotel.ServiceReference1.getAllResponse> getAllAsync() {
            MiltonHotel.ServiceReference1.getAllRequest inValue = new MiltonHotel.ServiceReference1.getAllRequest();
            inValue.Body = new MiltonHotel.ServiceReference1.getAllRequestBody();
            return ((MiltonHotel.ServiceReference1.Assignment3)(this)).getAllAsync(inValue);
        }
    }
}
